# Generated by Django 5.2.8 on 2026-07-10 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comercio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=20)),
                ('nombre_comercial', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=255)),
                ('contacto', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('volumen_90d', models.FloatField()),
                ('estado', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.FloatField()),
                ('stock', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('imagen_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ruta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(max_length=100)),
                ('capacidad_max', models.IntegerField()),
                ('vehiculo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Incentivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('umbral_min', models.FloatField()),
                ('umbral_max', models.FloatField()),
                ('descuento_pct', models.FloatField()),
                ('activo', models.BooleanField(default=True)),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incentivos', to='plataforma.comercio')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('estado', models.CharField(max_length=50)),
                ('monto_total', models.FloatField()),
                ('descuento', models.FloatField()),
                ('sincronizado', models.BooleanField(default=False)),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='plataforma.comercio')),
            ],
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(max_length=50)),
                ('mensaje', models.CharField(max_length=255)),
                ('enviado_en', models.DateTimeField()),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='plataforma.comercio')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='plataforma.pedido')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='plataforma.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='plataforma.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_estimada', models.DateTimeField()),
                ('fecha_real', models.DateTimeField(blank=True, null=True)),
                ('tipo_confirmacion', models.CharField(max_length=50)),
                ('evidencia_url', models.CharField(blank=True, max_length=255, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='plataforma.pedido')),
                ('ruta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='plataforma.ruta')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('password_hash', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=50)),
                ('ultima_sesion', models.DateTimeField()),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='plataforma.comercio')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='plataforma.usuario'),
        ),
    ]
