# Generated by Django 5.2.7 on 2026-07-12 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plataforma', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlantillaIncentivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('umbral_min', models.FloatField()),
                ('umbral_max', models.FloatField()),
                ('descuento_pct', models.FloatField()),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['umbral_min'],
            },
        ),
        migrations.CreateModel(
            name='ReglaCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('Estandar', 'Comercio Estandar'), ('Preferente', 'Comercio Preferente'), ('Estrategico', 'Comercio Estrategico')], max_length=20, unique=True)),
                ('volumen_min', models.FloatField()),
                ('bono_descuento_pct', models.FloatField(default=0)),
                ('beneficio_descripcion', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ['volumen_min'],
            },
        ),
        migrations.CreateModel(
            name='ReglaFrecuencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventana_dias', models.IntegerField(default=30)),
                ('pedidos_minimos', models.IntegerField(default=4)),
                ('puntos_por_dolar', models.FloatField(default=1)),
                ('bono_puntos', models.IntegerField(default=50)),
                ('activa', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='MovimientoPuntos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField()),
                ('motivo', models.CharField(max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('comercio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimientos_puntos', to='plataforma.comercio')),
                ('pedido', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimientos_puntos', to='plataforma.pedido')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='PuntosFidelidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField(default=0)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('comercio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='puntos_fidelidad', to='plataforma.comercio')),
            ],
        ),
    ]
