# Generated by Django 5.2.8 on 2026-07-12 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("plataforma", "0003_seed_reglas_incentivos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="comercio",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="usuarios",
                to="plataforma.comercio",
            ),
        ),
    ]
